language: elixir
elixir:
  - '1.8.2'
  - '1.9.3'
  - '1.10.4'
  - '1.11.0'
otp_release:
  - '21.3'
  - '22.2'
  - '23.0'
matrix:
  exclude: # Incompatible releases
    - elixir: 1.8.2
      otp_release: 23.0
    - elixir: 1.9.3
      otp_release: 23.0
